/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import static ventanas.Vendedor.cboCliente;

/**
 *
 * @author f3r
 */
public class Encuesta extends javax.swing.JFrame {
    ButtonGroup clima= new ButtonGroup();
    ButtonGroup atraccion = new ButtonGroup();
    ButtonGroup disfrute = new ButtonGroup();
    
    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagen/icono.png")).getImage());
        //con este código la ventana aparece en el centro de la pantalla al ser inicializada
        this.setLocationRelativeTo(this);
        
        //Se agregan los rbutton al grupo clima
        clima.add(rbtFiro);
        clima.add(rbtCalido);
        clima.add(rbtTemplado);
        //Se deseleccionan todos los rbutton del grupo clima
        
        //Se agregan los rbutton al grupo atraccion
        atraccion.add(rbtAventura);
        atraccion.add(rbtFantasia);
        atraccion.add(rbtHistoria);
        
        //Se agregan los rbutton al grupo disfrute
        disfrute.add(rbtComida);
        disfrute.add(rbtPaisaje);
        disfrute.add(rbtAmbos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rbtFiro = new javax.swing.JRadioButton();
        rbtTemplado = new javax.swing.JRadioButton();
        rbtCalido = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbtAventura = new javax.swing.JRadioButton();
        rbtHistoria = new javax.swing.JRadioButton();
        rbtFantasia = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtComida = new javax.swing.JRadioButton();
        rbtPaisaje = new javax.swing.JRadioButton();
        rbtAmbos = new javax.swing.JRadioButton();
        btnIr = new javax.swing.JButton();
        btnNoGracias = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENCUESTA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("¿Qué clima te gusta?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 149, 38));

        rbtFiro.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtFiro.setText("Frío");
        rbtFiro.setOpaque(false);
        getContentPane().add(rbtFiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 85, -1, -1));

        rbtTemplado.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtTemplado.setText("Templado");
        rbtTemplado.setOpaque(false);
        getContentPane().add(rbtTemplado, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 85, -1, -1));

        rbtCalido.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtCalido.setText("Cálido");
        rbtCalido.setOpaque(false);
        getContentPane().add(rbtCalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 85, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("¿Qué te atrae más?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 149, 38));

        rbtAventura.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtAventura.setText("Aventura");
        rbtAventura.setOpaque(false);
        getContentPane().add(rbtAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, -1, -1));

        rbtHistoria.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtHistoria.setText("Historia");
        rbtHistoria.setOpaque(false);
        getContentPane().add(rbtHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 168, -1, -1));

        rbtFantasia.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtFantasia.setText("Fantasía");
        rbtFantasia.setOpaque(false);
        getContentPane().add(rbtFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 168, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("¿Qué disfrutas más en un viaje?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, 219, 38));

        rbtComida.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtComida.setText("Comida");
        rbtComida.setOpaque(false);
        getContentPane().add(rbtComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 251, -1, -1));

        rbtPaisaje.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtPaisaje.setText("Paisaje");
        rbtPaisaje.setOpaque(false);
        getContentPane().add(rbtPaisaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 251, -1, -1));

        rbtAmbos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbtAmbos.setText("Ambos");
        rbtAmbos.setOpaque(false);
        getContentPane().add(rbtAmbos, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 251, -1, -1));

        btnIr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIr.setText("IR");
        btnIr.setBorderPainted(false);
        btnIr.setOpaque(false);
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });
        getContentPane().add(btnIr, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 330, 71, -1));

        btnNoGracias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNoGracias.setText("NO,  GRACIAS");
        btnNoGracias.setBorderPainted(false);
        btnNoGracias.setOpaque(false);
        btnNoGracias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoGraciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoGracias, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoGraciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoGraciasActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnNoGraciasActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnNoGracias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtAmbos;
    private javax.swing.JRadioButton rbtAventura;
    private javax.swing.JRadioButton rbtCalido;
    private javax.swing.JRadioButton rbtComida;
    private javax.swing.JRadioButton rbtFantasia;
    private javax.swing.JRadioButton rbtFiro;
    private javax.swing.JRadioButton rbtHistoria;
    private javax.swing.JRadioButton rbtPaisaje;
    private javax.swing.JRadioButton rbtTemplado;
    // End of variables declaration//GEN-END:variables
}
