//Grupo
package ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author f3r
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        
        //Con este código la ventana aparece en el centro de la pantalla al ser inicializada
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        btnPuntos = new javax.swing.JButton();
        btnViajeImaginario = new javax.swing.JButton();
        lblImagenIndex = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RINA KARUTA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Bienvenidos a RINA KARUTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 204, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n     Empresa de viaje que convierte tu sueño\n      de viajar en una experiencia única e\n                  inolvidable.\n\n     Travel company that turns your dream of\n           traveling into a unique and \n                  unforgettable\n                   experience.\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 430, 190));

        btnRegistrar.setBackground(new java.awt.Color(255, 204, 0));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setText("REGISTRARSE");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, -1));

        btnPuntos.setBackground(new java.awt.Color(255, 204, 0));
        btnPuntos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPuntos.setText("VIAJE CON PUNTOS");
        btnPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        btnViajeImaginario.setBackground(new java.awt.Color(255, 204, 0));
        btnViajeImaginario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViajeImaginario.setText("VIAJE IMAGINARIO");
        getContentPane().add(btnViajeImaginario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, -1));

        lblImagenIndex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/nubes.jpg"))); // NOI18N
        getContentPane().add(lblImagenIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        //Se crea un objeto llamado registro para poder manipular la ventana Registro
        Registro registro = new Registro();
        
        //Se inicializa la ventana Registro
        registro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntosActionPerformed
        //Se muestra una ventana predeterminada mostrando el mensaje: "Acumula puntos ...."
        JOptionPane.showMessageDialog(null, "Acumula puntos y gana viajes gratis de hasta 1,500 S/.\n"
                + "\t\tConoce esta increíble promoción. ","PUNTOS", JOptionPane.PLAIN_MESSAGE);

        //Se crea un objeto llamado punto para poder manipular la ventana ViajeConPuntos
        ViajeConPuntos punto= new ViajeConPuntos();
        
        //Se inicializa la ventana ViajeConPuntos
        punto.setVisible(true);
    }//GEN-LAST:event_btnPuntosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPuntos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnViajeImaginario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblImagenIndex;
    // End of variables declaration//GEN-END:variables
}
