//grupo
package ventanas;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import static ventanas.Vendedor.cboCliente;

/**
 *
 * @author f3r
 */
public class Registro extends javax.swing.JFrame {

    // se crea variable de tipo entero para contar los clientes registrados
    int c;
    
    //Se crea la variable doc para indicar la posición del commobox de documento de identidad
    int doc;
    
    //se crean vectores para que almacenen los datos de cada cliente
    String []nom= new String[50];
    String []ape= new String[50];
    String []dni = new String[50];
    String []tlf = new String[50];
    String []mail = new String[50];
    
    // se crean objetos datos,term,encues para manipular las ventanas Vendedor,Terminos,Encuesta
    Vendedor datos = new Vendedor();
    Terminos term=new Terminos();
    Encuesta encues=new Encuesta();
    
    
    public Registro() {
        initComponents();
        
        //con este código la ventana aparece en el centro de la pantalla al ser inicializada
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboDocumento = new javax.swing.JComboBox<>();
        txtDNI = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        chkTermi = new javax.swing.JCheckBox();
        btnVer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTelef = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        lblFondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 37, 70, 27));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 134, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, 70, 27));

        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 134, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telef.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 172, 70, 27));

        cboDocumento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Documento", "DNI", "Pasaporte", "Carnet de Extranjería" }));
        cboDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(cboDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        txtDNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDNI.setEnabled(false);
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 134, 27));

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 102, 32));

        chkTermi.setText("Acepto Términos y Condiciones");
        chkTermi.setEnabled(false);
        chkTermi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTermiActionPerformed(evt);
            }
        });
        getContentPane().add(chkTermi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnVer.setText("Ver");
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 217, 70, 27));

        txtTelef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTelef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 134, 27));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 134, 27));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setEnabled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 30));

        lblFondoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/avion.jpg"))); // NOI18N
        getContentPane().add(lblFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //se crea un método llamado obtener que guarda los datos que se ingresan en cada textfield
    private void obtener(){
        nom[c]=txtNombre.getText();
        ape[c]=txtApellido.getText();
        dni[c]=txtDNI.getText();
        tlf[c]=txtTelef.getText();
        mail[c]=txtEmail.getText();
    }
        
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        // se llama al método obtener
        
        datos.nom[c]=nom[c]+" "+ape[c];
        //
        datos.dni[c]=dni[c];
        //
        datos.tlf[c]=tlf[c];
        //
        datos.mail[c]=mail[c];
        
        //cada vez q se de clic al botón enviar se sumará 1 a la variable c
        c++;
        
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtDNI.setEnabled(false);
        txtTelef.setEnabled(false);
        txtEmail.setEnabled(false);
        chkTermi.setEnabled(false);
        btnVer.setEnabled(false);
        
        //Se muestra una ventana predeterminada de netbeans mostrando el mensaje: Su registro ha sido exitoso
        JOptionPane.showMessageDialog(null, "\t"+nom[c-1]+", su registro ha sido exitoso.","REGISTRO",JOptionPane.PLAIN_MESSAGE);
        btnEnviar.setEnabled(true);
        
        //Se abre la ventana del vendedor
        datos.setVisible(true);
        
        //Se abre la ventana de encuesta
        encues.setVisible(true);
        //Se deseleccionan todos los rbutton del grupo clima de la ventana encuesta
        encues.clima.clearSelection();
        //Se deseleccionan todos los rbutton del grupo atraccion de la ventana encuesta
        encues.atraccion.clearSelection();
        //Se deseleccionan todos los rbutton del grupo disfrute de la ventana encuesta
        encues.disfrute.clearSelection();
        
        //Se hace un bucle para que agregue en el combobox del vendedor la cantidad de clientes que se van registrando
        for ( int i = 0; i < c ; i++) { 
            cboCliente.addItem("0"+(i+1));  
        }
        
        //Se habilita el botón nuevo
        btnNuevo.setEnabled(true);
        
    }//GEN-LAST:event_btnEnviarActionPerformed
    
    
    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
         // Se muestra la ventana de los términos
        term.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void chkTermiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTermiActionPerformed
        //Se hace una condición que permita habilitar el botón enviar solo si el cliente acepta los términos y condiciones
        if (chkTermi.isSelected()) {
            btnEnviar.setEnabled(true);
            
        }else{
            btnEnviar.setEnabled(false);
            
        }
    }//GEN-LAST:event_chkTermiActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelefActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // se llama al método obtener
        this.obtener();
        
       //se crea un bucle en donde se verifique si existe algún @ en el campo de e-mail
        for (int i = 0; i < mail[c].length(); i++) {    
                if( (mail[c].charAt(i)=='@')){
                //si existe arroba se habilitará el checkbox para aceptar los términos y ocndiciones
                chkTermi.setEnabled(true);
                break;
                }
                else{
                //sino existe arroba no se habilita ese checkbox
                    chkTermi.setEnabled(false);
                }
            }
    }//GEN-LAST:event_txtEmailActionPerformed

    private void cboDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDocumentoActionPerformed
        //Se determina la posición seleccionada en el combobox de documento y el valor lo toma la variable doc
        doc=cboDocumento.getSelectedIndex();
        if (doc!=0) {
            txtDNI.setEnabled(true);
        } else{
            txtDNI.setEnabled(false);
        }
    }//GEN-LAST:event_cboDocumentoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // Se borran todos los items escritos en el combobox
        cboCliente.removeAllItems();

        //Se escribe como primer item la palabra Seleccionar
        cboCliente.addItem("Seleccionar");

        //se habilita el botón Ver de términos y condiciones
        btnVer.setEnabled(true);

        //se deshabilitan el boton enviar yel checkbox para aceptar terminos y condiciones
        btnEnviar.setEnabled(false);
        chkTermi.setSelected(false);

        // se borra lo que estaba escrito del registro anterior
        txtNombre.setText("");
        txtApellido.setText("");
        cboDocumento.setSelectedIndex(0); //vuelve al primer item del combo box
        txtDNI.setText("");
        txtTelef.setText("");
        txtEmail.setText("");

        //se habilitan los campos de texto para ingresar un nuevo registro
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtDNI.setEnabled(false);
        txtTelef.setEnabled(true);
        txtEmail.setEnabled(true);

        //se inhabilita el botón nuevo
        btnNuevo.setEnabled(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEnviar;
    public static javax.swing.JButton btnNuevo;
    public static javax.swing.JButton btnVer;
    public static javax.swing.JComboBox<String> cboDocumento;
    public static javax.swing.JCheckBox chkTermi;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel lblFondoRegistro;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtDNI;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelef;
    // End of variables declaration//GEN-END:variables
}
