/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.ActionEvent;
import static ventanas.Vendedor.cboCliente;

/**
 *
 * @author f3r
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    
    int c;
    String []nom= new String[50];
    String []ape= new String[50];
    String []dni = new String[50];
    String []tlf = new String[50];
    String []mail = new String[50];
    
    Vendedor datos = new Vendedor();
    Terminos term=new Terminos();
    Encuesta encues=new Encuesta();
    
    
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        chkTermi = new javax.swing.JCheckBox();
        btnVer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelef = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblRegistro = new javax.swing.JLabel();
        lblFondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 37, 70, 27));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 134, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, 70, 27));

        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 134, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telef.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 172, 70, 27));

        txtDNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 134, 27));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 102, 32));

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 102, 32));

        chkTermi.setText("Acepto Términos y Condiciones");
        chkTermi.setEnabled(false);
        chkTermi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTermiActionPerformed(evt);
            }
        });
        getContentPane().add(chkTermi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnVer.setText("Ver");
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 127, 60, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 217, 70, 27));

        txtTelef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTelef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 134, 27));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 134, 27));

        lblRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 318, 21));

        lblFondoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/avion.jpg"))); // NOI18N
        getContentPane().add(lblFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void obtener(){
        mail[c]=txtEmail.getText();
        tlf[c]=txtTelef.getText();
        nom[c]=txtNombre.getText();
        ape[c]=txtApellido.getText();
        dni[c]=txtDNI.getText();
        
    }
    
    private void condi(){
            for (int i = 0; i < mail[c].length(); i++) {    
                if( (mail[c].charAt(i)=='@')){
                chkTermi.setEnabled(true);
                break;
                }
                else{    
                    chkTermi.setEnabled(false);
                }
            }
    }    
        
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         
        this.obtener();
        
        datos.nom[c]=nom[c]+" "+ape[c];
        
        //
        datos.dni[c]=dni[c];
        c++;
        
        
        
        //txtNombre.setEnabled(false);
        //txtApellido.setEnabled(false);
        //txtDNI.setEnabled(false);
        txtTelef.setEnabled(false);
        //txtEmail.setEnabled(false);
        lblRegistro.setText("Su registro ha sido exitoso.");
        //chkTermi.setEnabled(false);
        btnVer.setEnabled(false);
        //btnGuardar.setEnabled(false);
        btnEnviar.setEnabled(true);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        datos.setVisible(true);
        encues.setVisible(true);
        
        cboCliente.addItem("Seleccionar");
        
        for ( int i = 0; i < c ; i++) {
            cboCliente.addItem("0"+(i+1));   
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed
    
    
    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        
        term.setVisible(true);
        
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void chkTermiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTermiActionPerformed
        // TODO add your handling code here:
        if (chkTermi.isSelected()) {
            btnGuardar.setEnabled(true);
            
        }else{
            btnGuardar.setEnabled(false);
            
        }
    }//GEN-LAST:event_chkTermiActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelefActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        this.obtener();
        this.condi();
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEnviar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnVer;
    public static javax.swing.JCheckBox chkTermi;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel lblFondoRegistro;
    public static javax.swing.JLabel lblRegistro;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtDNI;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelef;
    // End of variables declaration//GEN-END:variables
}
